services:
  golang-server:
    container_name: ${COMPOSE_PROJECT_NAME}-golang-server
    build:
      context: ./server
      dockerfile: server.dockerfile
    secrets:
      - publicKey
      - privateKey
    # restart: always
    network_mode: host
    environment:
      CONFIG_SERVER__LISTEN_ADDRESS: ${CONFIG_SERVER__LISTEN_ADDRESS}
      CONFIG_SERVER__ALLOWED_ORIGINS: ${CONFIG_SERVER__ALLOWED_ORIGINS}
      CONFIG_SERVER__JWT_PRIVATE_KEY_PATH: ${CONFIG_SERVER__JWT_PRIVATE_KEY_PATH}
      CONFIG_SERVER__JWT_PUBLIC_KEY_PATH: ${CONFIG_SERVER__JWT_PUBLIC_KEY_PATH}
      CONFIG_SERVER__RESET_REDIRECT_URL: ${CONFIG_SERVER__RESET_REDIRECT_URL}
      CONFIG_SERVER__GOOGLE_EMAIL_PASSWORD: ${CONFIG_SERVER__GOOGLE_EMAIL_PASSWORD}
      CONFIG_SERVER__GOOGLE_SERVICE: ${CONFIG_SERVER__GOOGLE_SERVICE}
      CONFIG_SERVER__GMAIL_HOST: ${CONFIG_SERVER__GMAIL_HOST}
      CONFIG_SERVER__GMAIL_PORT: ${CONFIG_SERVER__GMAIL_PORT}
      CONFIG_SERVER__EMAIL_PORT: ${CONFIG_SERVER__EMAIL_PORT}
      CONFIG_SERVER__FROM_EMAIL: ${CONFIG_SERVER__FROM_EMAIL}
      CONFIG_CLOUDINARY__CLOUD_NAME: ${CONFIG_CLOUDINARY__CLOUD_NAME}
      CONFIG_CLOUDINARY__API_KEY: ${CONFIG_CLOUDINARY__API_KEY}
      CONFIG_CLOUDINARY__API_SECRET: ${CONFIG_CLOUDINARY__API_SECRET}
      CONFIG_CLOUDINARY__BASE_DELIVERY_URL: ${CONFIG_CLOUDINARY__BASE_DELIVERY_URL}
      CONFIG_CLOUDINARY__SECRETE_DELIVERY_URL: ${CONFIG_CLOUDINARY__SECRETE_DELIVERY_URL}
      CONFIG_CLOUDINARY__API_BASE_URL: ${CONFIG_CLOUDINARY__API_BASE_URL}
      CONFIG_CLOUDINARY__API_PROVISIONING_URL: ${CONFIG_CLOUDINARY__API_PROVISIONING_URL}
      CONFIG_CLOUDINARY__URL: ${CONFIG_CLOUDINARY__URL}
      CONFIG_SERVER__DATABASE_URL: ${CONFIG_SERVER__DATABASE_URL}
      CONFIG_SERVER__DB_HOST: ${CONFIG_SERVER__DB_HOST}
      CONFIG_SERVER__DB_USER: ${CONFIG_SERVER__DB_USER}
      CONFIG_SERVER__DB_NAME: ${CONFIG_SERVER__DB_NAME}
      CONFIG_SERVER__DB_PORT: ${CONFIG_SERVER__DB_PORT}
      CONFIG_SERVER__DB_PASSWORD: ${CONFIG_SERVER__DB_PASSWORD}
      # CONFIG_AWS__FOLDER_LIST: ${CONFIG_AWS__FOLDER_LIST}
      # CONFIG_AWS__REGION: ${CONFIG_AWS__REGION}
      # CONFIG_AWS__BUCKET_NAME: ${CONFIG_AWS__BUCKET_NAME}
      # CONFIG_AWS__BASE_PATH: ${CONFIG_AWS__BASE_PATH}
  # volumes:
  #   - /home/c5roger/project_fo/my_projects/hackaton_project/backend/server
secrets:
  publicKey:
    file: ./keys/jwt.pub.pem
  privateKey:
    file: ./keys/jwt.key
